### PR TITLE
NEXUS-27617

### PR DESCRIPTION
**Pull request by joedragons**
For @dbradicich re https://issues.sonatype.org/browse/NEXUS-27617

### CODE REVIEW

**Comment by dbradicich** [comment]
Just to add a bit of detail, this PR is simply adding a new recipe `3x-docker`, which is nearly identical to rh-docker, the only difference being that the java recipe has been removed.  So that our Dockerfile can introduce a specific build of openjdk8 (as the current 8u292 that the java recipe is bringing in has a bug, so we need to force 8u282 in place, and sadly the java recipe only lets you select major version, not minor.  The docker PR for ref https://github.com/sonatype/docker-nexus3/pull/129

**Review by Blacktiger — APPROVED** [review]

**Review by anubistheta — APPROVED** [review]
Looks good, but I'm no expert in chef/ruby.

**Comment by dbradicich** [comment]
> but I'm no expert in chef/ruby.

No worries @anubistheta, neither am I !!  :P

**Comment by joedragons** [comment]
Supererceded by #60

**Pull request closed without merging**
